version: '3'
services:
  node:
    build: .
    # image: "us.gcr.io/rfpselectdev/rfpselect-service:latest"
    # command: yarn debug
    command: yarn start
    ports:
      - "8001:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - WP_URL=http://wp/wp-json
      # - DEBUG=rfpselect-service:*
    volumes: 
      - ./controllers:/usr/src/app/controllers

networks:
  default:
    external:
      name: rfpselect-network

    