version: '3'
services:
  node:
    build: .
    # image: "us.gcr.io/rfpselectdev/rfpselect-service:latest"
    ports:
      - "8001:3000"
    environment:
      - env=development
      - NODE_ENV=production
    networks:
      default:
        external:
          name: rfpselect-network

      