kind: Service
apiVersion: v1
metadata:
  name: rfpselect-frontend
spec:
  type: LoadBalancer
  ports:
  - name: "8002"
    port: 8002
    targetPort: 80
    protocol: TCP
  selector:
    app: rfpselect
    role: frontend