apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rfpselect-frontend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: frontend-layer
      labels:
        app: rfpselect
        role: frontend
        env: development
    spec:
      containers:
        - image: us.gcr.io/rfpselectdev/rfpselect-frontend:1.0.0
          name: fronted-layer-node
          ports:
          - containerPort: 80
          env:
            - name: "NODE_ENV"
              value: "development"