apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rfpselect-service-layer-prod
spec:
  replicas: 1
  template:
    metadata:
      name: service
      labels:
        app: rfpselect
        role: service-layer
        env: development
    spec:
      containers:
        - image: us.gcr.io/rfpselectdev/rfpselect-service:1.0.0
          name: service-layer-node
          ports:
          - containerPort: 3000
          env:
            - name: "NODE_ENV"
              value: "development"